import { M, ctx, C0, C1, C2, C3, txt, fr, sr, state } from '../engine/state.js';

export const IV = {
            n:"INVADERS", st:'START', sc:0, lvs:3, pX:100, bs:[], aBs:[], as:[], aD:1, aSp:500, mT:0,
            ini(){ this.st='START'; this.sc=0; this.lvs=3; this.res(); },
            res(){ this.as=[]; this.bs=[]; this.aBs=[]; this.pX=100; this.aD=1; this.aSp=500; this.mT=0; for(let r=0;r<4;r++)for(let c=0;c<6;c++)this.as.push({x:30+c*25,y:30+r*18,t:r}); },
            upd(dt){ if(this.st!=='PLAYING')return; this.pX=M.max(10,M.min(190,state.k.L?this.pX-0.15*dt:state.k.R?this.pX+0.15*dt:this.pX)); for(let i=this.bs.length-1;i>=0;i--){this.bs[i].y-=0.25*dt;if(this.bs[i].y<0)this.bs.splice(i,1);} for(let i=this.aBs.length-1;i>=0;i--){this.aBs[i].y+=0.15*dt;if(this.aBs[i].y>200)this.aBs.splice(i,1);} this.mT+=dt; if(this.mT>this.aSp){ this.mT=0; let hE=0; for(let a of this.as)if((this.aD===1&&a.x>180)||(this.aD===-1&&a.x<20))hE=1; if(hE){ this.aD*=-1; for(let a of this.as){ a.y+=10; if(a.y>=170)this.st='GAMEOVER'; } this.aSp=M.max(100,this.aSp-30); }else{ for(let a of this.as)a.x+=this.aD*8; } if(this.as.length>0&&M.random()<.4){ let s=this.as[~~(M.random()*this.as.length)]; this.aBs.push({x:s.x,y:s.y+5}); } } for(let i=this.bs.length-1;i>=0;i--){ let b=this.bs[i], ht=0; for(let j=this.as.length-1;j>=0;j--){ let a=this.as[j]; if(M.abs(b.x-a.x)<10&&M.abs(b.y-a.y)<8){ this.as.splice(j,1); ht=1; this.sc+=10; break; } } if(ht)this.bs.splice(i,1); } for(let i=this.aBs.length-1;i>=0;i--){ let b=this.aBs[i]; if(M.abs(b.x-this.pX)<8&&M.abs(b.y-180)<6){ this.lvs--; this.aBs.splice(i,1); if(this.lvs<=0)this.st='GAMEOVER'; } } if(!this.as.length){ this.res(); this.lvs=M.min(5,this.lvs+1); } },
            inp(b){ if(this.st==='START'||this.st==='GAMEOVER'){if(b==='ST'||b==='A'){this.ini();this.st='PLAYING';}}else if(this.st==='PLAYING'){if((b==='A'||b==='B')&&this.bs.length<3)this.bs.push({x:this.pX,y:172});} },
            drw(){ if(this.st==='START'){txt("INVADERS",100,20,16);txt("PRESS START",100,140,8);return;} txt(`SC:${this.sc}`,5,12,8,'left'); txt(`LIVES:${this.lvs}`,135,12,8,'left'); ctx.fillStyle=C0; ctx.beginPath(); ctx.moveTo(this.pX,174); ctx.lineTo(this.pX+8,184); ctx.lineTo(this.pX-8,184); ctx.fill(); for(let a of this.as){ fr(a.x-6,a.y-4,12,8,a.t%2===0?C1:C0); fr(a.x-4,a.y-6,8,2); fr(a.x-8,a.y,2,4); fr(a.x+6,a.y,2,4); fr(a.x-4,a.y-2,2,2,C3); fr(a.x+2,a.y-2,2,2,C3); } for(let b of this.bs)fr(b.x-1,b.y-4,2,6,C0); for(let b of this.aBs)fr(b.x-1,b.y-2,2,4,C1); if(this.st==='GAMEOVER'){ fr(10,60,180,80,'rgba(155,188,15,.9)'); sr(10,60,180,80,C0); txt("GAME OVER",100,85,12); txt(`SC:${this.sc}`,100,105,10); } },
            art(x,y,w,h){ fr(x,y,w,h,C3); sr(x,y,w,h,C0); let cx=x+w/2, cy=y+h/2; fr(cx-8,cy-6,16,10,C0); fr(cx-6,cy-10,12,4,C0); fr(cx-4,cy-4,2,2,C3); fr(cx+2,cy-4,2,2,C3); }
        };